### ISSUE TITLE
"five" is not printed following example

### ISSUE THREAD

**Issue by midnightcodr** [peterhaldbaek/delimiter-stream#1]
Hi, I tried your "Using the data event" example but the result doesn't work exactly the same as yours, it prints the following
> one
> two
> three
> four

Note 'five' is not printed, any idea why?

**Comment by peterhaldbaek** [comment]
Strange. I have a unit test testing a similar scenario which seems to work. But data is not exactly the same. Maybe you could try running the tests by executing `npm test`? Which Node version and OS are you using?

**Comment by midnightcodr** [comment]
I think I know why. In your test, https://github.com/peterhaldbaek/delimiter-stream/blob/master/test/test.js#L91 makes a difference. In your README.md, if you have `delimiterstream.end();` right after the last `write()` the result would include 'five'.

**Comment by peterhaldbaek** [comment]
Nice catch! I'll fix the documentation. Thanks for letting me know. 👍
